import test from 'node:test';
import assert from 'node:assert/strict';
import { generateSlots } from '../src/slots.mjs';
import { validateCompleteness } from '../src/completeness.mjs';
const expectedIdentity={currentArtifactId:'3bba19e0be936e7b9d3554ac737d32f5cf84c846',currentRenderSha256:'c'.repeat(64),absentRenderSha256:'a'.repeat(64)};
function slots(){return generateSlots({qualificationId:'q',taskIds:['T1'],trialIndices:[0]}).map((slot,i)=>({...slot,judgeBlindId:`jb-${String(i+1).repeat(64)}`}));}
function evidence(slot,overrides={}){const responseSha256=overrides.responseSha256??'d'.repeat(64);return{slotId:slot.slotId,qualificationId:slot.qualificationId,taskId:slot.taskId,conditionId:slot.conditionId,trialIndex:slot.trialIndex,activation:slot.activation,surface:slot.surface,artifactIdentity:slot.conditionId==='CURRENT_PRYZAEL'?expectedIdentity.currentArtifactId:'NONE',conditionRenderSha256:slot.conditionId==='CURRENT_PRYZAEL'?expectedIdentity.currentRenderSha256:expectedIdentity.absentRenderSha256,responseSha256,hostProfileDigest:'h'.repeat(64),judgeResult:{judgeBlindId:slot.judgeBlindId,responseSha256,trialResult:{status:'OPAQUE'}},...overrides};}
test('accepts complete paired evidence',()=>{const expectedSlots=slots();assert.deepEqual(validateCompleteness({expectedSlots,evidence:expectedSlots.map(evidence),expectedIdentity}),{total:2,NO_PRYZAEL:1,CURRENT_PRYZAEL:1,pairedHostProfiles:1});});
test('rejects missing, duplicate, and unexpected slots',()=>{const expectedSlots=slots();const records=expectedSlots.map(evidence);assert.throws(()=>validateCompleteness({expectedSlots,evidence:records.slice(1),expectedIdentity}),/missing slot/);assert.throws(()=>validateCompleteness({expectedSlots,evidence:[...records,records[0]],expectedIdentity}),/duplicate slot/);assert.throws(()=>validateCompleteness({expectedSlots,evidence:[...records,{...records[0],slotId:'unexpected'}],expectedIdentity}),/unexpected slot/);});
test('rejects frozen trial identity drift',()=>{const expectedSlots=slots();for(const [field,value] of [['qualificationId','wrong'],['taskId','wrong'],['conditionId','CURRENT_PRYZAEL'],['trialIndex',99],['activation','OTHER'],['surface','OTHER']]){const records=expectedSlots.map(evidence);records[0][field]=value;assert.throws(()=>validateCompleteness({expectedSlots,evidence:records,expectedIdentity}),new RegExp(`${field} mismatch`));}});
test('rejects artifact, render, response, Judge, and paired-host mismatches',()=>{const expectedSlots=slots();const base=expectedSlots.map(evidence);for(const [mutate,pattern] of [[r=>r[0].artifactIdentity='wrong',/artifact identity mismatch/],[r=>r[1].conditionRenderSha256='0'.repeat(64),/condition render digest mismatch/],[r=>r[0].judgeResult.responseSha256='e'.repeat(64),/response digest mismatch/],[r=>r[0].judgeResult.judgeBlindId=`jb-${'9'.repeat(64)}`,/Judge identity mismatch/],[r=>r[1].hostProfileDigest='x'.repeat(64),/host-profile mismatch/]]){const records=structuredClone(base);mutate(records);assert.throws(()=>validateCompleteness({expectedSlots,evidence:records,expectedIdentity}),pattern);}});
test('does not interpret TrialResult verdict semantics',()=>{const expectedSlots=slots();const records=expectedSlots.map((slot,i)=>evidence(slot,{judgeResult:{judgeBlindId:slot.judgeBlindId,responseSha256:'d'.repeat(64),trialResult:{arbitraryFrozenSemantics:i}}}));assert.doesNotThrow(()=>validateCompleteness({expectedSlots,evidence:records,expectedIdentity}));});
