import test from 'node:test';
import assert from 'node:assert/strict';
import { generateSlots } from '../src/slots.mjs';
const api=await import('../src/completeness.mjs').catch(()=>({}));
const expectedIdentity=Object.freeze({currentArtifactId:'3bba19e0be936e7b9d3554ac737d32f5cf84c846',currentRenderSha256:'c'.repeat(64),absentRenderSha256:'a'.repeat(64)});
function expectedSlots(){return generateSlots({qualificationId:'q',taskIds:['T1'],conditions:['NO_PRYZAEL','CURRENT_PRYZAEL'],trialIndices:[0]}).map((slot,i)=>({...slot,judgeBlindId:`jb-${String(i+1).repeat(64)}`}));}
function evidenceFor(slot,overrides={}){const responseSha256=overrides.responseSha256??'d'.repeat(64);return{slotId:slot.slotId,qualificationId:slot.qualificationId,taskId:slot.taskId,conditionId:slot.conditionId,trialIndex:slot.trialIndex,artifactIdentity:slot.conditionId==='CURRENT_PRYZAEL'?expectedIdentity.currentArtifactId:'NONE',conditionRenderSha256:slot.conditionId==='CURRENT_PRYZAEL'?expectedIdentity.currentRenderSha256:expectedIdentity.absentRenderSha256,responseSha256,hostProfileDigest:'h'.repeat(64),judgeResult:{judgeBlindId:slot.judgeBlindId,responseSha256,trialResult:{status:'OPAQUE-TO-CARRIER'}},...overrides};}
test('exports completeness API and accepts a complete paired evidence set',()=>{const slots=expectedSlots();assert.deepEqual(api.validateCompleteness({expectedSlots:slots,evidence:slots.map(evidenceFor),expectedIdentity}),{total:2,NO_PRYZAEL:1,CURRENT_PRYZAEL:1,pairedHostProfiles:1});});
test('rejects missing, duplicate, and unexpected slots',()=>{const slots=expectedSlots();const evidence=slots.map(evidenceFor);assert.throws(()=>api.validateCompleteness({expectedSlots:slots,evidence:evidence.slice(1),expectedIdentity}),/missing slot/);assert.throws(()=>api.validateCompleteness({expectedSlots:slots,evidence:[...evidence,evidence[0]],expectedIdentity}),/duplicate slot/);assert.throws(()=>api.validateCompleteness({expectedSlots:slots,evidence:[...evidence,{...evidence[0],slotId:'slot-unexpected'}],expectedIdentity}),/unexpected slot/);});
test('rejects identity and integrity mismatches',()=>{const slots=expectedSlots();const base=slots.map(evidenceFor);for(const [mutate,pattern] of [[e=>e[0].taskId='wrong',/taskId mismatch/],[e=>e[0].artifactIdentity='wrong',/artifact identity mismatch/],[e=>e[1].conditionRenderSha256='0'.repeat(64),/condition render digest mismatch/],[e=>e[0].judgeResult.responseSha256='e'.repeat(64),/response digest mismatch/],[e=>e[0].judgeResult.judgeBlindId=`jb-${'9'.repeat(64)}`,/Judge identity mismatch/],[e=>e[1].hostProfileDigest='x'.repeat(64),/host-profile mismatch/]]){const m=structuredClone(base);mutate(m);assert.throws(()=>api.validateCompleteness({expectedSlots:slots,evidence:m,expectedIdentity}),pattern);}});
test('does not interpret TrialResult verdict semantics',()=>{const slots=expectedSlots();const evidence=slots.map((slot,i)=>evidenceFor(slot,{judgeResult:{judgeBlindId:slot.judgeBlindId,responseSha256:'d'.repeat(64),trialResult:{arbitraryFrozenSemantics:i}}}));assert.doesNotThrow(()=>api.validateCompleteness({expectedSlots:slots,evidence,expectedIdentity}));});
