import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { gitBlobSha1 } from '../src/frozen-source.mjs';
const api=await import('../src/condition-renderer.mjs').catch(()=>({})); const sha256=(bytes)=>createHash('sha256').update(bytes).digest('hex');
function syntheticManifest(){ const rows=[['skills/a/SKILL.md',Buffer.from('A without newline')],['skills/a/references/z.md',Buffer.from('Z\r\n')]]; return { identity:{repository:'4i7/Pryzael',sourceCommit:'c'.repeat(40),sourceTree:'t'.repeat(40),canonicalSkillsTree:'s'.repeat(40),pluginVersion:'0.3.0'}, rendererVersion:'r4c-condition-render-v1', rendererImplementationSha256:null, entries:rows.map(([path,bytes])=>({path,blobSha1:gitBlobSha1(bytes),byteCount:bytes.length,sha256:sha256(bytes)})), _material:new Map(rows)}; }
test('exports deterministic renderer API',()=>{ assert.equal(typeof api.renderCurrent,'function'); assert.equal(typeof api.renderAbsent,'function'); assert.equal(typeof api.rendererImplementationSha256,'function'); });
test('CURRENT rendering is deterministic, ordinal and exact-byte bound',()=>{ const manifest=syntheticManifest(); manifest.rendererImplementationSha256=api.rendererImplementationSha256(); const first=api.renderCurrent({materialByPath:manifest._material,manifest}); const second=api.renderCurrent({materialByPath:new Map([...manifest._material].reverse()),manifest}); assert.deepEqual(first.conditionBytes,second.conditionBytes); assert.equal(first.conditionRenderSha256,second.conditionRenderSha256); assert.equal(first.conditionRenderSha256,sha256(first.conditionBytes)); assert.equal(first.semanticByteCount,Buffer.byteLength('A without newline')+Buffer.byteLength('Z\r\n')); assert.ok(first.conditionBytes.indexOf(Buffer.from('skills/a/SKILL.md'))<first.conditionBytes.indexOf(Buffer.from('skills/a/references/z.md'))); manifest.conditionRenderSha256=first.conditionRenderSha256; assert.doesNotThrow(()=>api.renderCurrent({materialByPath:manifest._material,manifest})); manifest.conditionRenderSha256='0'.repeat(64); assert.throws(()=>api.renderCurrent({materialByPath:manifest._material,manifest}),/condition render digest mismatch/); });
test('CURRENT rejects missing material and renderer implementation drift',()=>{ const manifest=syntheticManifest(); manifest.rendererImplementationSha256=api.rendererImplementationSha256(); const missing=new Map(manifest._material); missing.delete('skills/a/SKILL.md'); assert.throws(()=>api.renderCurrent({materialByPath:missing,manifest}),/missing path/); manifest.rendererImplementationSha256='f'.repeat(64); assert.throws(()=>api.verifyRendererImplementation(manifest),/renderer implementation digest mismatch/); });
test('NO condition uses the same carrier class with zero semantic bytes',()=>{ const absent=api.renderAbsent(); assert.equal(absent.state,'ABSENT'); assert.equal(absent.semanticByteCount,0); assert.equal(absent.semanticBytes.length,0); assert.match(absent.conditionBytes.toString('utf8'),/^R4C-CONDITION r4c-condition-render-v1\nSTATE ABSENT\nSEMANTIC-BYTES 0\n/); assert.equal(absent.conditionRenderSha256,sha256(absent.conditionBytes)); assert.ok(!absent.conditionBytes.toString('utf8').includes('NO_PRYZAEL')); assert.ok(!absent.conditionBytes.toString('utf8').includes('CURRENT_PRYZAEL')); });
