import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
const api = await import('../src/frozen-source.mjs').catch(() => ({}));
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const gitBlob = (bytes) => createHash('sha1').update(Buffer.from(`blob ${bytes.length}\0`)).update(bytes).digest('hex');
const expectedIdentity = Object.freeze({ repository: '4i7/Pryzael', sourceCommit: 'c'.repeat(40), sourceTree: 't'.repeat(40), canonicalSkillsTree: 's'.repeat(40), pluginVersion: '0.3.0' });
function manifestFor(entries) { return { identity: expectedIdentity, entries: entries.map(([path,text]) => { const bytes=Buffer.from(text,'utf8'); return { path, blobSha1:gitBlob(bytes), byteCount:bytes.length, sha256:sha256(bytes) }; }).sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0) }; }
test('exports frozen-source verification API',()=>{ assert.equal(typeof api.verifyFrozenIdentity,'function'); assert.equal(typeof api.verifyInventory,'function'); assert.equal(typeof api.gitBlobSha1,'function'); });
test('accepts only the exact frozen identity',()=>{ assert.equal(api.verifyFrozenIdentity(expectedIdentity,expectedIdentity),true); for(const key of ['repository','sourceCommit','sourceTree','canonicalSkillsTree','pluginVersion']) assert.throws(()=>api.verifyFrozenIdentity({...expectedIdentity,[key]:`${expectedIdentity[key]}-wrong`},expectedIdentity),new RegExp(key)); });
test('verifies exact bytes, Git blob, byte count, SHA-256 and path set',()=>{ const manifest=manifestFor([['skills/a/SKILL.md','alpha\n'],['skills/a/references/x.md','βeta\r\n']]); const material=new Map([['skills/a/SKILL.md',Buffer.from('alpha\n')],['skills/a/references/x.md',Buffer.from('βeta\r\n')]]); assert.deepEqual(api.verifyInventory(material,manifest).map(e=>e.path),manifest.entries.map(e=>e.path)); const changed=new Map(material); changed.set('skills/a/SKILL.md',Buffer.from('alpha changed\n')); assert.throws(()=>api.verifyInventory(changed,manifest),/blobSha1|byteCount|sha256/); const missing=new Map(material); missing.delete('skills/a/SKILL.md'); assert.throws(()=>api.verifyInventory(missing,manifest),/missing path/); const unexpected=new Map(material); unexpected.set('skills/r5-candidate/SKILL.md',Buffer.from('candidate')); assert.throws(()=>api.verifyInventory(unexpected,manifest),/unexpected path/); });
test('Git blob hashing binds exact bytes',()=>{ assert.equal(api.gitBlobSha1(Buffer.from('hello\n')),gitBlob(Buffer.from('hello\n'))); assert.notEqual(api.gitBlobSha1(Buffer.from('hello\r\n')),api.gitBlobSha1(Buffer.from('hello\n'))); });
test('canonical manifest digest fails closed on any bound-field change',()=>{ const manifest={ identity:expectedIdentity, rendererVersion:'r4c-condition-render-v1', rendererImplementationSha256:'r'.repeat(64), entries:manifestFor([['skills/a/SKILL.md','x']]).entries, conditionRenderSha256:'c'.repeat(64) }; manifest.manifestSha256=api.computeManifestSha256(manifest); assert.equal(api.verifyManifestDigest(manifest),true); assert.throws(()=>api.verifyManifestDigest({...manifest,conditionRenderSha256:'d'.repeat(64)}),/manifest digest mismatch/); });
test('loads only manifest-bound model-visible paths and rejects extra semantic resources',async(t)=>{ const {mkdtemp,mkdir,writeFile,rm}=await import('node:fs/promises'); const {tmpdir}=await import('node:os'); const {join}=await import('node:path'); const root=await mkdtemp(join(tmpdir(),'r4c-source-')); t.after(()=>rm(root,{recursive:true,force:true})); await mkdir(join(root,'skills/a/references'),{recursive:true}); await writeFile(join(root,'skills/a/SKILL.md'),'alpha\n'); await writeFile(join(root,'skills/a/references/x.md'),'beta\n'); const manifest=manifestFor([['skills/a/SKILL.md','alpha\n'],['skills/a/references/x.md','beta\n']]); assert.equal(api.loadFrozenMaterial(root,manifest).size,2); await writeFile(join(root,'skills/a/references/r5-candidate.md'),'candidate\n'); assert.throws(()=>api.loadFrozenMaterial(root,manifest),/unexpected model-visible path/); });
