import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { gitBlobSha1, verifyManifestDigest } from '../src/frozen-source.mjs';
const api=await import('../src/frozen-manifest.mjs').catch(()=>({}));
const identity={repository:'repo',sourceCommit:'c',sourceTree:'t',canonicalSkillsTree:'s',pluginVersion:'v'}; const bytes=Buffer.from('semantic\r\nbytes'); const expectedPathBlobs=[{path:'skills/a/SKILL.md',blobSha1:gitBlobSha1(bytes),byteCount:bytes.length}];
test('builds a manifest that binds per-path SHA-256, renderer, rendered bytes and canonical digest',()=>{ assert.equal(typeof api.buildFrozenManifestFromMaterial,'function'); const manifest=api.buildFrozenManifestFromMaterial({actualIdentity:identity,expectedIdentity:identity,materialByPath:new Map([['skills/a/SKILL.md',bytes]]),expectedPathBlobs,rendererImplementationSha256:createHash('sha256').update('renderer').digest('hex'),rendererSourceVerification:false}); assert.equal(manifest.entries[0].sha256,createHash('sha256').update(bytes).digest('hex')); assert.equal(manifest.conditionRenderSha256.length,64); assert.equal(manifest.manifestSha256.length,64); assert.equal(verifyManifestDigest(manifest),true); });
test('fails closed on wrong blob metadata before rendering',()=>{ assert.throws(()=>api.buildFrozenManifestFromMaterial({actualIdentity:identity,expectedIdentity:identity,materialByPath:new Map([['skills/a/SKILL.md',bytes]]),expectedPathBlobs:[{...expectedPathBlobs[0],blobSha1:'0'.repeat(40)}],rendererImplementationSha256:'r'.repeat(64),rendererSourceVerification:false}),/blobSha1 mismatch/); });
test('fails closed if repeated renderer executions differ',()=>{ assert.equal(typeof api.assertDeterministicCurrentRender,'function'); let n=0; const fakeRenderer=()=>{ n+=1; const conditionBytes=Buffer.from(`render-${n}`,'utf8'); return {conditionBytes,conditionRenderSha256:createHash('sha256').update(conditionBytes).digest('hex')}; }; assert.throws(()=>api.assertDeterministicCurrentRender({materialByPath:new Map(),manifest:{},renderCurrentFn:fakeRenderer}),/renderer nondeterminism/); });
