import test from 'node:test';
import assert from 'node:assert/strict';
import { sha256Hex, stableJson } from '../src/hash.mjs';
import { deriveJudgeBlindId, generateSlots } from '../src/slots.mjs';

test('generates exact 42-slot structural baseline and four public slots',()=>{const baseline=generateSlots({qualificationId:'q',taskIds:['T7','T1','T4','T3','T2','T6','T5'],trialIndices:[0,1,2]});assert.equal(baseline.length,42);assert.equal(new Set(baseline.map(s=>s.slotId)).size,42);const publicSlots=generateSlots({qualificationId:'public-r4c-dry-run-v1',taskIds:['DEV-REPLAN-001','DEV-SIMPLE-001'],trialIndices:[0]});assert.equal(publicSlots.length,4);});
test('binds frozen activation and surface into every slot identity',()=>{const [slot]=generateSlots({qualificationId:'q',taskIds:['A'],conditions:['CURRENT_PRYZAEL'],trialIndices:[0]});assert.equal(slot.activation,'CONDITIONED_BEHAVIOR');assert.equal(slot.surface,'NATIVE');const incomplete={qualificationId:slot.qualificationId,taskId:slot.taskId,conditionId:slot.conditionId,trialIndex:slot.trialIndex};assert.notEqual(slot.slotId,`slot-${sha256Hex(stableJson(incomplete)).slice(0,32)}`);});
test('rejects duplicate or malformed slot dimensions',()=>{const base={qualificationId:'q',taskIds:['A'],conditions:['NO_PRYZAEL','CURRENT_PRYZAEL'],trialIndices:[0]};assert.throws(()=>generateSlots({...base,taskIds:['A','A']}),/duplicate task/);assert.throws(()=>generateSlots({...base,conditions:['CURRENT_PRYZAEL','R5_CANDIDATE']}),/unsupported condition/);});
test('Judge blind IDs are deterministic HMAC values with no condition token',()=>{const [slot]=generateSlots({qualificationId:'q',taskIds:['A'],conditions:['CURRENT_PRYZAEL'],trialIndices:[0]});const key=Buffer.from('private-key-32-bytes-minimum-0000');const a=deriveJudgeBlindId(slot,key);assert.equal(a,deriveJudgeBlindId(slot,key));assert.match(a,/^jb-[0-9a-f]{64}$/);assert.ok(!a.includes('CURRENT'));assert.throws(()=>deriveJudgeBlindId(slot,Buffer.from('short')),/blinding key/);});
